name: ci-golang-workflow

on: 
  pull_request:
    branches: [develop]

jobs:
  check-application:
    name: golang-ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.25.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.25.3
        
      - name: Run tests
        run: go test

      - name: Run app
        run: go run math.go
